name: douglas_peucker
description: >
  polyline simplification  it uses a combination of Douglas-Peucker and Radial Distance algorithms.
  Polyline simplification dramatically reduces the number of points in a polyline while retaining its shape, giving a huge performance boost when processing it and also reducing visual noise. For example, it's essential when rendering a 70k-points line chart or a map route in the browser using Canvas or SVG.
version: 0.0.4
author: Darwin Morocho <dsmr.apps@gmail.com>
homepage: https://github.com/MorochoRochaDarwin/douglas-peucker-dart
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0